### PR TITLE
Rename `Vector(Approx)` -> `VectorSpace(Approx)`.

### PR DESCRIPTION
**Pull request by sebcrozet**
Also bumps the cargo version number.

### CODE REVIEW

**Comment by brendanzab** [comment]
Good stuff. Have you seen the new structure of cgmath by the way?

**Comment by sebcrozet** [comment]
I have not, but now that you mention it, I will !

**Comment by sebcrozet** [comment]
Okay, I've quickly looked at it. I intended to add structures like `InnerVectorSpace`, and `NormedSpace` as well. However, `algebra` should go a bit further and assume that a vector space is not necessarily finite. So we need a `FiniteVectorSpace` trait here too before being able to talk about an `EuclideanSpace`.

**Comment by sebcrozet** [comment]
(Edit: by "finite", I meant "with a finite dimension")

**Comment by brendanzab** [comment]
Yep, definitely. Just thought I'd mention it! It's been a while since I did a pass over algebra, and my thinking has changed a bit since then...

**Pull request merged**
